vile:
  ignore:
    - LICENSE
    - appveyor.yml
    - coverage
    - coffeelint.json
    - .babelrc
    - .build
    - .npmignore
    - .travis.yml
    - .vim.custom
    - node_modules
    - lib
    - tags
    - .test
    - .ctags
    - .git
    - circle.yml
    - .editorconfig
    - .eslintignore
    - .eslintrc
    - .gitignore
    - .npmrc
    - tags
    - tmp
    - "/lib"
    - vendor
    - README.md
    - .vile.yml

depcheck:
  config:
    ignore_dev_deps: false
    ignore_dirs:
      - src
      - typings
      - node_modules
      - coverage
      - tmp
    ignore_deps:
      - mocha
      - babel-cli
      - coffee-script
      - istanbul
      - release-it
      - typescript
      - wrench
      - pryjs
      - shelljs
      - "vile-**"

coverage:
  config:
    path: coverage/lcov.info
